prog_cfg:
  bag_file: !!path /home/zyr/zyr/data/weijing_range.bag
  bag_rate: 0.0
  queue_size: 10

  gps_status_valid: 2

  # pointcloud2 | livox
  lidar_type: pointcloud2
  lidar_topic: /driver/hesai/pandar
  # lidar_topic: /driver/front/rslidar_points
  gps_topic: /Inertial/gps/fi

app_cfg:
  voxel_cfg:
    max_num_voxels: 100000
    max_num_points: 10
    resolution: 0.5
    min_distance: 0.1

  reg_cfg_track:
    max_iterations: 400
    robust_kernel: 0.0
    rotation_epsilon: 1e-3
    translation_epsilon: 1e-3

  reg_cfg_loop:
    max_iterations: 400
    robust_kernel: 0.0
    rotation_epsilon: 1e-4
    translation_epsilon: 1e-4

  enable_deskew: false
  enable_loopclosure: false
  update_local_map: true

  # lidar -> gps
  extinct: [0, 1.15, -1.96]
  # extinct: []

  static_frames: 1
  range_min: 4
  range_max: 250
  tracking_voxel: 1.0
  mapping_voxel: 2.0

  loop_frame_skip: 600
  loop_trials_num: 10
  loop_distance_threshold: 20
  loop_interval_ms: 1000
  loop_overlap_threshold: 0.9
  loop_fitness_threshold: 0.1
  loop_local_frames: 1000